name: test

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.*'
      - 'docs/*'
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - 'README.*'
      - 'docs/*'

env:
  app-name: iconisor
  javafx-version: '14.0.1'

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
          java-package: jdk
          architecture: x64
      - name: Install xvfb
        run: sudo apt install -y xvfb
      - run: xvfb-run lein test
      - run: xvfb-run lein cloverage --codecov
      - uses: codecov/codecov-action@v1

  linter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmd:
          - 'cljfmt check'
          - 'eastwood'
          - 'kibit'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
          java-package: jdk
          architecture: x64
      - run: lein ${{ matrix.cmd }}

  build:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          # - runs-on: windows-latest
          #   os: windows
          # - runs-on: macOS-latest
          #   os: osx
          - runs-on: ubuntu-latest
            os: linux
    steps:
      - uses: actions/checkout@v2

      - name: Install lein (unix)
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.1.469'
          lein: 2.9.4
          boot: latest
        if: matrix.os != 'windows'

      - name: Install lein (windows)
        run: |
          from urllib import request
          import os
          lists = [
            ("https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/%s", "lein.bat"),
          ]
          for elem in lists:
            url = elem[0] % elem[1]
            file = elem[1]
            request.urlretrieve(url, file)
            os.system("lein.bat self-install")
        shell: python
        if: matrix.os == 'windows'

      - name: Install openjfx jmods
        run: |
          mkdir -p jmods
          curl -o jmods/jmods.zip -sSL https://download2.gluonhq.com/openjfx/${{ env.javafx-version }}/openjfx-${{ env.javafx-version }}_${{ matrix.os }}-x64_bin-jmods.zip
          (
            cd jmods
            unzip jmods.zip
          )

      - name: Initialize custom JRE
        run: ./jlink.sh jre

      - name: Build
        run: lein uberjar
      - name: Create artifact
        run: |
          mv jre .github/dist/* LICENSE target/uberjar/${{ env.app-name }}.jar ${{ env.app-name }}/
