name: test

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.*'
      - 'docs/*'
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - 'README.*'
      - 'docs/*'

env:
  app-name: iconisor
  javafx-version: '14.0.1'

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
          java-package: jdk
          architecture: x64
      - name: Install xvfb
        run: sudo apt install -y xvfb
      - run: xvfb-run lein test
      - run: xvfb-run lein cloverage --codecov
      - uses: codecov/codecov-action@v1

  linter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmd:
          - 'cljfmt check'
          - 'kibit'
    steps:
      - uses: actions/checkout@v2
      - run: lein ${{ matrix.cmd }}

  build:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - runs-on: windows-latest
            os: windows
          - runs-on: macOS-latest
            os: osx
          - runs-on: ubuntu-latest
            os: linux
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '14'
          java-package: jdk
          architecture: x64
      - name: Install lein (unix)
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.1.469'
          lein: 2.9.4
          boot: latest
        if: matrix.os != 'windows'

      - name: Install lein (windows)
        run: |
          from urllib import request
          import os
          lists = [
            ("https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/%s", "lein.bat"),
          ]
          for elem in lists:
            url = elem[0] % elem[1]
            file = elem[1]
            request.urlretrieve(url, file)
            os.system("lein.bat self-install")
        shell: python
        if: matrix.os == 'windows'

      - name: Install openjfx jmods
        run: |
          mkdir -p jmods
          curl -o jmods/jmods.zip -sSL https://download2.gluonhq.com/openjfx/${{ env.javafx-version }}/openjfx-${{ env.javafx-version }}_${{ matrix.os }}-x64_bin-jmods.zip
          (
            cd jmods
            unzip jmods.zip
          )

      - name: Initialize custom JRE
        run: ./jlink.sh jre

      - name: Build (unix)
        run: lein uberjar
        if: matrix.os != 'windows'

      - name: Build (windows)
        run: lein.bat uberjar
        if: matrix.os == 'windows'
        shell: cmd

      - name: Create artifact
        run: |
          mkdir -p ${{ env.app-name }}_${{ matrix.os }}/
          mv jre .github/dist/* LICENSE target/uberjar/${{ env.app-name }}.jar ${{ env.app-name }}_${{ matrix.os }}/

      - name: Compress artifact (unix)
        run: |
          tar czf ${{ env.app-name }}_${{ matrix.os }}.tar.gz ${{ env.app-name }}_${{ matrix.os }}
        if: matrix.os != 'windows'

      - name: Compress artifact (windows)
        run: |
          7z a ${{ env.app-name }}_${{ matrix.os }}.zip ${{ env.app-name }}_${{ matrix.os }}
        if: matrix.os == 'windows'

      - uses: actions/upload-artifact@v2
        with:
          name: artifact-${{ matrix.os }}
          path: |
            ${{ env.app-name }}_${{ matrix.os }}/*.tar.gz
            ${{ env.app-name }}_${{ matrix.os }}/*.zip
        if: startsWith(github.ref, 'refs/tags/')

  create-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v1
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Write upload_url to file
        run: echo '${{ steps.create-release.outputs.upload_url }}' > upload_url.txt

      - uses: actions/upload-artifact@v2
        with:
          name: create-release
          path: upload_url.txt

  upload-release:
    runs-on: ubuntu-latest
    needs: create-release
    strategy:
      matrix:
        include:
          - os: windows
            asset_name_suffix: windows.zip
            asset_content_type: application/zip
          - os: osx
            asset_name_suffix: osx.tar.gz
            asset_content_type: application/gzip
          - os: linux
            asset_name_suffix: linux.tar.gz
            asset_content_type: application/gzip
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact-${{ matrix.os }}

      - uses: actions/download-artifact@v2
        with:
          name: create-release

      - id: vars
        run: |
          echo "::set-output name=upload_url::$(cat upload_url.txt)"
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.vars.outputs.upload_url }}
          asset_path: ${{ env.app-name }}_${{ matrix.asset_name_suffix }}
          asset_name: ${{ env.app-name }}_${{ matrix.asset_name_suffix }}
          asset_content_type: ${{ matrix.asset_content_type }}
